version: "3.5"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    environment:
      FLASK_APP: app
      FLASK_ENV: development