version: "3.5"

services:
  web:
    build:
      dockerfile: Dockerfile.web
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@db/postgres

  worker:
    build:
      dockerfile: Dockerfile.worker
      context: .
    volumes:
      - ".:/app"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db/postgres

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"